# services:
#   backend:
#     build: .
#     ports:
#       - "3000:3000"
#   frontend:
#     build: ./projeto-devops
#     ports:
#       - "3001:3000"


services:
  frontend:
    build: ./path/to/frontend
    ports:
      - "3000:3000"
  backend:
    build: ./path/to/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

