# services:
#   backend:
#     build: .
#     ports:
#       - "3000:3000"
#   frontend:
#     build: ./projeto-devops
#     ports:
#       - "3001:3000"



# version: '3.7'
# services:
#   backend:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       DB_HOST: db
#       DB_USER: root
#       DB_PASSWORD: example
#       DB_NAME: mydatabase
#       NODE_ENV: production
#       PORT: 3000
#   frontend:
#     build: ./projeto-devops
#     ports:
#       - "3001:3000"
#     environment:
#       REACT_APP_BACKEND_URL: http://localhost:3000










version: '3'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
